[package]
name = "kak-tabs"
description = "kakoune tabs"
license = "CC0-1.0"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/enricozb/tree-sitter.kak"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.5", features = ["derive"] }
