[package]
name = "kak-tabs"
description = "kakoune tabs"
license = "CC0-1.0"
version = "0.1.7"
edition = "2021"
repository = "https://github.com/enricozb/tabs.kak"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive"] }
